from micropython import const

# Define the constant of percussion timbre type for channel 9.The notes with the suffix "STANDARD_SET" use the default "standard set" sound.

# Percussion timbre type 1
# 打击音色类型1
MIDI_PERCUSSION_TIMBRE_1: int = const(0)

# Percussion timbre type 2
# 打击音色类型2
MIDI_PERCUSSION_TIMBRE_2: int = const(16)

# Percussion timbre type 3
# 打击音色类型3
MIDI_PERCUSSION_TIMBRE_3: int = const(40)

# Percussion timbre type 4
# 打击音色类型4
MIDI_PERCUSSION_TIMBRE_4: int = const(48)

# Percussion timbre type 5
# 打击音色类型5
MIDI_PERCUSSION_TIMBRE_5: int = const(127)

# Define the note constants for percussion timbre type 1 in channel 9.
# ===== 打击音色类型1的音符常量 =====

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_1_STANDARD_SET: int = const(27)
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_1_STANDARD_SET: int = const(28)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_1_STANDARD_SET: int = const(29)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_1_STANDARD_SET: int = const(30)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_1_STANDARD_SET: int = const(31)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_1_STANDARD_SET: int = const(32)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_1_STANDARD_SET: int = const(33)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_1_STANDARD_SET: int = const(34)

# B1 (Kick drum 2)
# 底鼓音色2
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_1_KICK_DRUM_2: int = const(35)

# C2 (Kick drum 1)
# 底鼓音色1
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_2_KICK_DRUM_1: int = const(36)

# C#2 (Side stick)
# 边击
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_2_SIDE_STICK: int = const(37)

# D2 (Snare drum 1)
# 军鼓音色1
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_2_SNARE_DRUM_1: int = const(38)

# D#2 (Hand clap)
# 拍手
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_2_HAND_CLAP: int = const(39)

# E2 (Snare drum 2)
# 军鼓音色2
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_2_SNARE_DRUM_2: int = const(40)

# F2 (Low floor tom)
# 低地通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_2_LOW_FLOOR_TOM: int = const(41)

# F#2 (Closed hi-hat)
# 闭合踩镲
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_2_CLOSED_HI_HAT: int = const(42)

# G2 (High floor tom)
# 高地通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_2_HIGH_FLOOR_TOM: int = const(43)

# G#2 (Pedal hi-hat)
# 踏板踩镲
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_2_PEDAL_HI_HAT: int = const(44)

# A2 (Low tom)
# 低通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_2_LOW_TOM: int = const(45)

# A#2 (Open hi-hat)
# 开镲
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_2_OPEN_HI_HAT: int = const(46)

# B2 (Low middle tom)
# 低中通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_2_LOW_MIDDLE_TOM: int = const(47)

# C3 (High middle tom)
# 高中通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_3_HIGH_MIDDLE_TOM: int = const(48)

# C#3 (Crash cymbal 1)
# 碎音镲音色1
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_3_CRASH_CYMBAL_1: int = const(49)

# D3 (High tom)
# 高通鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_3_HIGH_TOM: int = const(50)

# D#3 (Ride cymbal 1)
# 叮音镲音色1
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_3_RIDE_CYMBAL_1: int = const(51)

# E3 (Chinese cymbal)
# 中国镲
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_3_CHINESE_CYMBAL: int = const(52)

# F3 (Ride bell)
# 浮音镲碗
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_3_RIDE_BELL: int = const(53)

# F#3 (Tambourine)
# 铃鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_3_TAMBOURINE: int = const(54)

# G3 (Splash cymbal)
# 溅音镲
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_3_SPLASH_CYMBAL: int = const(55)

# G#3 (Cowbell)
# 牛铃
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_3_COWBELL: int = const(56)

# A3 (Crash cymbal 2)
# 碎音镲音色2
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_3_CRASH_CYMBAL_2: int = const(57)

# A#3 (Vibra slap)
# 颤音叉
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_3_VIBRA_SLAP: int = const(58)

# B3 (Ride cymbal 2)
# 叮音镲音色2
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_3_RIDE_CYMBAL_2: int = const(59)

# C4 (High bongo)
# 高音邦戈鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_4_HIGH_BONGO: int = const(60)

# C#4 (Low bongo)
# 低音邦戈鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_4_LOW_BONGO: int = const(61)

# D4 (Mute high conga)
# 闷音高音康加鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_4_MUTE_HIGH_CONGA: int = const(62)

# D#4 (Open high conga)
# 开放高音康加鼓	
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_4_OPEN_HIGH_CONGA: int = const(63)

# E4 (Low conga)
# 低音康加鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_4_LOW_CONGA: int = const(64)

# F4 (High timbale)
# 高定音鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_4_HIGH_TIMBALE: int = const(65)

# F#4 (Low timbale)
# 低定音鼓
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_4_LOW_TIMBALE: int = const(66)

# G4 (High agogo)
# 高音阿戈戈铃	
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_4_HIGH_AGOGO: int = const(67)

# G#4 (Low agogo)
# 低音阿戈戈铃
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_4_LOW_AGOGO: int = const(68)

# A4 (Cabasa)
# 卡巴萨
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_4_CABASA: int = const(69)

# A#4 (Maracas)
# 沙槌
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_4_MARACAS: int = const(70)

# B4 (Short whistle)
# 短哨
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_4_SHORT_WHISTLE: int = const(71)

# C5 (Long whistle)
# 长哨
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_5_LONG_WHISTLE: int = const(72)

# C#5 (Short guiro)
# 短刮瓜
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_5_SHORT_GUIRO: int = const(73)

# D5 (Long guiro)
# 长刮瓜
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_5_LONG_GUIRO: int = const(74)

# D#5 (Claves)
# 响棒
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_5_CLAVES: int = const(75)

# E5 (High wood block)
# 高音木鱼
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_5_HIGH_WOOD_BLOCK: int = const(76)

# F5 (Low wood block)
# 低音木鱼
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_5_LOW_WOOD_BLOCK: int = const(77)

# F#5 (Mute cuica)
# 弱音锯琴
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_5_MUTE_CUICA: int = const(78)

# G5 (Open cuica)
# 开放锯琴
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_5_OPEN_CUICA: int = const(79)

# G#5 (Mute triangle)
# 弱音三角铁
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_5_MUTE_TRIANGLE: int = const(80)

# A5 (Open triangle)
# 开放三角铁
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_5_OPEN_TRIANGLE: int = const(81)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_5_STANDARD_SET: int = const(82)
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_5_STANDARD_SET: int = const(83)
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_6_STANDARD_SET: int = const(84)
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_6_STANDARD_SET: int = const(85)
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_6_STANDARD_SET: int = const(86)
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_6_STANDARD_SET: int = const(87)
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_6_STANDARD_SET: int = const(88)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_6_STANDARD_SET: int = const(89)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_6_STANDARD_SET: int = const(90)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_6_STANDARD_SET: int = const(91)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_6_STANDARD_SET: int = const(92)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_6_STANDARD_SET: int = const(93)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_6_STANDARD_SET: int = const(94)
MIDI_PERCUSSION_TIMBRE_1_NOTE_B_6_STANDARD_SET: int = const(95)
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_7_STANDARD_SET: int = const(96)
MIDI_PERCUSSION_TIMBRE_1_NOTE_C_SHARP_7_STANDARD_SET: int = const(97)
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_7_STANDARD_SET: int = const(98)
MIDI_PERCUSSION_TIMBRE_1_NOTE_D_SHARP_7_STANDARD_SET: int = const(99)
MIDI_PERCUSSION_TIMBRE_1_NOTE_E_7_STANDARD_SET: int = const(100)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_7_STANDARD_SET: int = const(101)
MIDI_PERCUSSION_TIMBRE_1_NOTE_F_SHARP_7_STANDARD_SET: int = const(102)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_7_STANDARD_SET: int = const(103)
MIDI_PERCUSSION_TIMBRE_1_NOTE_G_SHARP_7_STANDARD_SET: int = const(104)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_7_STANDARD_SET: int = const(105)
MIDI_PERCUSSION_TIMBRE_1_NOTE_A_SHARP_7_STANDARD_SET: int = const(106)

# Define the note constants for percussion timbre type 2 in channel 9.
# ===== 打击音色类型2的音符常量 =====

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_1_STANDARD_SET: int = const(27)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_1_STANDARD_SET: int = const(28)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_1_STANDARD_SET: int = const(29)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_1_STANDARD_SET: int = const(30)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_1_STANDARD_SET: int = const(31)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_1_STANDARD_SET: int = const(32)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_1_STANDARD_SET: int = const(33)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_1_STANDARD_SET: int = const(34)
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_1_STANDARD_SET: int = const(35)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_2_STANDARD_SET: int = const(36)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_2_STANDARD_SET: int = const(37)

# D2 (Gated snare)
# 门控军鼓
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_2_GATED_SNARE: int = const(38)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_2_STANDARD_SET: int = const(39)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_2_STANDARD_SET: int = const(40)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_2_STANDARD_SET: int = const(41)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_2_STANDARD_SET: int = const(42)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_2_STANDARD_SET: int = const(43)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_2_STANDARD_SET: int = const(44)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_2_STANDARD_SET: int = const(45)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_2_STANDARD_SET: int = const(46)

# B2 (Gun shot)
# 枪声
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_2_GUN_SHOT: int = const(47)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_3_STANDARD_SET: int = const(48)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_3_STANDARD_SET: int = const(49)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_3_STANDARD_SET: int = const(50)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_3_STANDARD_SET: int = const(51)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_3_STANDARD_SET: int = const(52)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_3_STANDARD_SET: int = const(53)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_3_STANDARD_SET: int = const(54)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_3_STANDARD_SET: int = const(55)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_3_STANDARD_SET: int = const(56)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_3_STANDARD_SET: int = const(57)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_3_STANDARD_SET: int = const(58)
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_3_STANDARD_SET: int = const(59)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_4_STANDARD_SET: int = const(60)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_4_STANDARD_SET: int = const(61)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_4_STANDARD_SET: int = const(62)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_4_STANDARD_SET: int = const(63)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_4_STANDARD_SET: int = const(64)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_4_STANDARD_SET: int = const(65)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_4_STANDARD_SET: int = const(66)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_4_STANDARD_SET: int = const(67)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_4_STANDARD_SET: int = const(68)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_4_STANDARD_SET: int = const(69)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_4_STANDARD_SET: int = const(70)
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_4_STANDARD_SET: int = const(71)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_5_STANDARD_SET: int = const(72)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_5_STANDARD_SET: int = const(73)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_5_STANDARD_SET: int = const(74)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_5_STANDARD_SET: int = const(75)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_5_STANDARD_SET: int = const(76)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_5_STANDARD_SET: int = const(77)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_5_STANDARD_SET: int = const(78)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_5_STANDARD_SET: int = const(79)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_5_STANDARD_SET: int = const(80)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_5_STANDARD_SET: int = const(81)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_5_STANDARD_SET: int = const(82)
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_5_STANDARD_SET: int = const(83)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_6_STANDARD_SET: int = const(84)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_6_STANDARD_SET: int = const(85)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_6_STANDARD_SET: int = const(86)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_6_STANDARD_SET: int = const(87)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_6_STANDARD_SET: int = const(88)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_6_STANDARD_SET: int = const(89)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_6_STANDARD_SET: int = const(90)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_6_STANDARD_SET: int = const(91)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_6_STANDARD_SET: int = const(92)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_6_STANDARD_SET: int = const(93)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_6_STANDARD_SET: int = const(94)
MIDI_PERCUSSION_TIMBRE_2_NOTE_B_6_STANDARD_SET: int = const(95)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_7_STANDARD_SET: int = const(96)
MIDI_PERCUSSION_TIMBRE_2_NOTE_C_SHARP_7_STANDARD_SET: int = const(97)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_7_STANDARD_SET: int = const(98)
MIDI_PERCUSSION_TIMBRE_2_NOTE_D_SHARP_7_STANDARD_SET: int = const(99)
MIDI_PERCUSSION_TIMBRE_2_NOTE_E_7_STANDARD_SET: int = const(100)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_7_STANDARD_SET: int = const(101)
MIDI_PERCUSSION_TIMBRE_2_NOTE_F_SHARP_7_STANDARD_SET: int = const(102)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_7_STANDARD_SET: int = const(103)
MIDI_PERCUSSION_TIMBRE_2_NOTE_G_SHARP_7_STANDARD_SET: int = const(104)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_7_STANDARD_SET: int = const(105)
MIDI_PERCUSSION_TIMBRE_2_NOTE_A_SHARP_7_STANDARD_SET: int = const(106)

# Define the note constants for percussion timbre type 3 in channel 9.
# ===== 打击音色类型3的音符常量 =====

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_1_STANDARD_SET: int = const(27)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_1_STANDARD_SET: int = const(28)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_1_STANDARD_SET: int = const(29)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_1_STANDARD_SET: int = const(30)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_1_STANDARD_SET: int = const(31)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_1_STANDARD_SET: int = const(32)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_1_STANDARD_SET: int = const(33)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_1_STANDARD_SET: int = const(34)

# B1 (Jazz bass drum 2)
# 爵士底鼓音色2
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_1_JAZZ_BASS_DRUM_2: int = const(35)

# C2 (Jazz bass drum 1)
# 爵士底鼓音色1
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_2_JAZZ_BASS_DRUM_1: int = const(36)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_2_STANDARD_SET: int = const(37)

# D2 (Brush tap)
# 鼓刷轻击
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_2_BRUSH_TAP: int = const(38)

# D#2 (Brush slap)
# 鼓刷拍打
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_2_BRUSH_SLAP: int = const(39)

# E2 (Brush swirl)
# 鼓刷漩涡
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_2_BRUSH_SWIRL: int = const(40)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_2_STANDARD_SET: int = const(41)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_2_STANDARD_SET: int = const(42)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_2_STANDARD_SET: int = const(43)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_2_STANDARD_SET: int = const(44)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_2_STANDARD_SET: int = const(45)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_2_STANDARD_SET: int = const(46)
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_2_STANDARD_SET: int = const(47)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_3_STANDARD_SET: int = const(48)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_3_STANDARD_SET: int = const(49)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_3_STANDARD_SET: int = const(50)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_3_STANDARD_SET: int = const(51)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_3_STANDARD_SET: int = const(52)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_3_STANDARD_SET: int = const(53)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_3_STANDARD_SET: int = const(54)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_3_STANDARD_SET: int = const(55)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_3_STANDARD_SET: int = const(56)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_3_STANDARD_SET: int = const(57)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_3_STANDARD_SET: int = const(58)
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_3_STANDARD_SET: int = const(59)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_4_STANDARD_SET: int = const(60)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_4_STANDARD_SET: int = const(61)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_4_STANDARD_SET: int = const(62)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_4_STANDARD_SET: int = const(63)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_4_STANDARD_SET: int = const(64)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_4_STANDARD_SET: int = const(65)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_4_STANDARD_SET: int = const(66)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_4_STANDARD_SET: int = const(67)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_4_STANDARD_SET: int = const(68)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_4_STANDARD_SET: int = const(69)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_4_STANDARD_SET: int = const(70)
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_4_STANDARD_SET: int = const(71)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_5_STANDARD_SET: int = const(72)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_5_STANDARD_SET: int = const(73)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_5_STANDARD_SET: int = const(74)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_5_STANDARD_SET: int = const(75)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_5_STANDARD_SET: int = const(76)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_5_STANDARD_SET: int = const(77)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_5_STANDARD_SET: int = const(78)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_5_STANDARD_SET: int = const(79)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_5_STANDARD_SET: int = const(80)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_5_STANDARD_SET: int = const(81)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_5_STANDARD_SET: int = const(82)
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_5_STANDARD_SET: int = const(83)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_6_STANDARD_SET: int = const(84)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_6_STANDARD_SET: int = const(85)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_6_STANDARD_SET: int = const(86)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_6_STANDARD_SET: int = const(87)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_6_STANDARD_SET: int = const(88)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_6_STANDARD_SET: int = const(89)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_6_STANDARD_SET: int = const(90)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_6_STANDARD_SET: int = const(91)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_6_STANDARD_SET: int = const(92)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_6_STANDARD_SET: int = const(93)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_6_STANDARD_SET: int = const(94)
MIDI_PERCUSSION_TIMBRE_3_NOTE_B_6_STANDARD_SET: int = const(95)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_7_STANDARD_SET: int = const(96)
MIDI_PERCUSSION_TIMBRE_3_NOTE_C_SHARP_7_STANDARD_SET: int = const(97)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_7_STANDARD_SET: int = const(98)
MIDI_PERCUSSION_TIMBRE_3_NOTE_D_SHARP_7_STANDARD_SET: int = const(99)
MIDI_PERCUSSION_TIMBRE_3_NOTE_E_7_STANDARD_SET: int = const(100)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_7_STANDARD_SET: int = const(101)
MIDI_PERCUSSION_TIMBRE_3_NOTE_F_SHARP_7_STANDARD_SET: int = const(102)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_7_STANDARD_SET: int = const(103)
MIDI_PERCUSSION_TIMBRE_3_NOTE_G_SHARP_7_STANDARD_SET: int = const(104)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_7_STANDARD_SET: int = const(105)
MIDI_PERCUSSION_TIMBRE_3_NOTE_A_SHARP_7_STANDARD_SET: int = const(106)

# Define the note constants for percussion timbre type 4 in channel 9.
# ===== 打击音色类型4的音符常量 =====

# D#1 (Closed hi hat)
# 闭合踩镲
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_1_CLOSED_HI_HAT: int = const(27)

# E1 (Pedal hi hat)
# 踏板踩镲
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_1_PEDAL_HI_HAT: int = const(28)

# F1 (Open hi hat)
# 开镲
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_1_OPEN_HI_HAT: int = const(29)

# F#1 (Ride cymbal)
# 扬镲
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_1_RIDE_CYMBAL: int = const(30)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_1_STANDARD_SET: int = const(31)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_1_STANDARD_SET: int = const(32)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_1_STANDARD_SET: int = const(33)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_1_STANDARD_SET: int = const(34)
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_1_STANDARD_SET: int = const(35)

# C2 (Gun shot)
# 枪声
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_2_GUN_SHOT: int = const(36)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_2_STANDARD_SET: int = const(37)

# D2 (Snare drum 2)
# 军鼓音色2
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_2_SNARE_DRUM_2: int = const(38)

# D#2 (Castanets)
# 响板
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_2_CASTANETS: int = const(39)

# E2 (Snare drum 1)
# 军鼓音色1
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_2_SNARE_DRUM_1: int = const(40)

# F2 (Timpani 1)
# 定音鼓音色1
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_2_TIMPANI_1: int = const(41)

# F#2 (Timpani 2)
# 定音鼓音色2
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_2_TIMPANI_2: int = const(42)

# G2 (Timpani 3)
# 定音鼓音色3
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_2_TIMPANI_3: int = const(43)

# G#2 (Timpani 4)
# 定音鼓音色4
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_2_TIMPANI_4: int = const(44)

# A2 (Timpani 5)
# 定音鼓音色5
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_2_TIMPANI_5: int = const(45)

# A#2 (Timpani 6)
# 定音鼓音色6
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_2_TIMPANI_6: int = const(46)

# B2 (Timpani 7)
# 定音鼓音色7
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_2_TIMPANI_7: int = const(47)

# C3 (Timpani 8)
# 定音鼓音色8
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_3_TIMPANI_8: int = const(48)

# C#3 (Timpani 9)
# 定音鼓音色9
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_3_TIMPANI_9: int = const(49)

# D3 (Timpani 10)
# 定音鼓音色10
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_3_TIMPANI_10: int = const(50)

# D#3 (Timpani 11)
# 定音鼓音色11
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_3_TIMPANI_11: int = const(51)

# E3 (Timpani 12)
# 定音鼓音色12
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_3_TIMPANI_12: int = const(52)

# F3 (Timpani 13)
# 定音鼓音色13
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_3_TIMPANI_13: int = const(53)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_3_STANDARD_SET: int = const(54)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_3_STANDARD_SET: int = const(55)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_3_STANDARD_SET: int = const(56)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_3_STANDARD_SET: int = const(57)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_3_STANDARD_SET: int = const(58)
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_3_STANDARD_SET: int = const(59)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_4_STANDARD_SET: int = const(60)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_4_STANDARD_SET: int = const(61)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_4_STANDARD_SET: int = const(62)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_4_STANDARD_SET: int = const(63)
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_4_STANDARD_SET: int = const(64)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_4_STANDARD_SET: int = const(65)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_4_STANDARD_SET: int = const(66)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_4_STANDARD_SET: int = const(67)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_4_STANDARD_SET: int = const(68)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_4_STANDARD_SET: int = const(69)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_4_STANDARD_SET: int = const(70)
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_4_STANDARD_SET: int = const(71)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_5_STANDARD_SET: int = const(72)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_5_STANDARD_SET: int = const(73)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_5_STANDARD_SET: int = const(74)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_5_STANDARD_SET: int = const(75)
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_5_STANDARD_SET: int = const(76)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_5_STANDARD_SET: int = const(77)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_5_STANDARD_SET: int = const(78)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_5_STANDARD_SET: int = const(79)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_5_STANDARD_SET: int = const(80)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_5_STANDARD_SET: int = const(81)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_5_STANDARD_SET: int = const(82)
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_5_STANDARD_SET: int = const(83)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_6_STANDARD_SET: int = const(84)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_6_STANDARD_SET: int = const(85)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_6_STANDARD_SET: int = const(86)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_6_STANDARD_SET: int = const(87)

# E6 (Applauses)
# 掌声
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_6_APPLAUSES: int = const(88)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_6_STANDARD_SET: int = const(89)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_6_STANDARD_SET: int = const(90)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_6_STANDARD_SET: int = const(91)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_6_STANDARD_SET: int = const(92)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_6_STANDARD_SET: int = const(93)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_6_STANDARD_SET: int = const(94)
MIDI_PERCUSSION_TIMBRE_4_NOTE_B_6_STANDARD_SET: int = const(95)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_7_STANDARD_SET: int = const(96)
MIDI_PERCUSSION_TIMBRE_4_NOTE_C_SHARP_7_STANDARD_SET: int = const(97)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_7_STANDARD_SET: int = const(98)
MIDI_PERCUSSION_TIMBRE_4_NOTE_D_SHARP_7_STANDARD_SET: int = const(99)
MIDI_PERCUSSION_TIMBRE_4_NOTE_E_7_STANDARD_SET: int = const(100)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_7_STANDARD_SET: int = const(101)
MIDI_PERCUSSION_TIMBRE_4_NOTE_F_SHARP_7_STANDARD_SET: int = const(102)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_7_STANDARD_SET: int = const(103)
MIDI_PERCUSSION_TIMBRE_4_NOTE_G_SHARP_7_STANDARD_SET: int = const(104)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_7_STANDARD_SET: int = const(105)
MIDI_PERCUSSION_TIMBRE_4_NOTE_A_SHARP_7_STANDARD_SET: int = const(106)

# Define the note constants for percussion timbre type 5 in channel 9.
# ===== 打击音色类型5的音符常量 =====

# B1 (Kick drum 1)
# 底鼓音色1
MIDI_PERCUSSION_TIMBRE_5_NOTE_B_1_KICK_DRUM_1: int = const(35)

# C2 (Kick drum 2)
# 底鼓音色2
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_2_KICK_DRUM_2: int = const(36)

# C#2 (Rim shot)
# 边击
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_SHARP_2_RIM_SHOT: int = const(37)

# D2 (Snare drum)
# 军鼓
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_2_SNARE_DRUM: int = const(38)

# D#2 (Hand clap)
# 拍手
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_SHARP_2_HAND_CLAP: int = const(39)

# E2 (Electric snare drum)
# 电子军鼓
MIDI_PERCUSSION_TIMBRE_5_NOTE_E_2_ELECTRIC_SNARE_DRUM: int = const(40)

# F2 (Acoustic low tom 1)
# 原声低音嗵鼓音色1
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_2_ACOUSTIC_LOW_TOM_1: int = const(41)

# F#2 (Closed hi hat)
# 闭合踩镲
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_SHARP_2_CLOSED_HI_HAT: int = const(42)

# G2 (Acoustic low tom 2)
# 原声低音嗵鼓音色2
MIDI_PERCUSSION_TIMBRE_5_NOTE_G_2_ACOUSTIC_LOW_TOM_2: int = const(43)

# G#2 (Open hi hat 2)
# 开镲音色2
MIDI_PERCUSSION_TIMBRE_5_NOTE_G_SHARP_2_OPEN_HI_HAT_2: int = const(44)

# A2 (Acoustic middle tom 1)
# 原声中音嗵鼓音色1
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_2_ACOUSTIC_MIDDLE_TOM_1: int = const(45)

# A#2 (Open hi hat 1)
# 开镲音色1
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_SHARP_2_OPEN_HI_HAT_1: int = const(46)

# B2 (Acoustic middle tom 2)
# 原声中音嗵鼓音色2
MIDI_PERCUSSION_TIMBRE_5_NOTE_B_2_ACOUSTIC_MIDDLE_TOM_2: int = const(47)

# C3 (Acoustic high tom 1)
# 原声高音嗵鼓音色1
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_3_ACOUSTIC_HIGHT_TOM_1: int = const(48)

# C#3 (Crash cymbal)
# 碎音镲
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_SHARP_3_CRASH_CYMBAL: int = const(49)

# D3 (Acoustic high tom 2)
# 原声高音嗵鼓音色2
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_3_ACOUSTIC_HIGH_TOM_2: int = const(50)

# D#3 (Ride cymbal)
# 节奏镲
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_SHARP_3_RIDE_CYMBAL: int = const(51)

# F#3 (Tambourine)
# 铃鼓
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_SHARP_3_TAMBOURINE: int = const(54)

# G#3 (Cowbell)
# 牛铃
MIDI_PERCUSSION_TIMBRE_5_NOTE_G_SHARP_3_COWBELL: int = const(56)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_4_STANDARD_SET: int = const(60)
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_SHARP_4_STANDARD_SET: int = const(61)
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_4_STANDARD_SET: int = const(62)
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_SHARP_4_STANDARD_SET: int = const(63)
MIDI_PERCUSSION_TIMBRE_5_NOTE_E_4_STANDARD_SET: int = const(64)
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_4_STANDARD_SET: int = const(65)
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_SHARP_4_STANDARD_SET: int = const(66)
MIDI_PERCUSSION_TIMBRE_5_NOTE_G_4_STANDARD_SET: int = const(67)
MIDI_PERCUSSION_TIMBRE_5_NOTE_G_SHARP_4_STANDARD_SET: int = const(68)
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_4_STANDARD_SET: int = const(69)
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_SHARP_4_STANDARD_SET: int = const(70)
MIDI_PERCUSSION_TIMBRE_5_NOTE_B_4_STANDARD_SET: int = const(71)
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_5_STANDARD_SET: int = const(72)

# C#5 (Vibra slap)
# 颤音叉
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_SHARP_5_VIBRA_SLAP: int = const(73)

# D#5 (Claves)
# 响棒
MIDI_PERCUSSION_TIMBRE_5_NOTE_D_SHARP_5_CLAVES: int = const(75)

# A#5 (Applauses)
# 掌声
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_SHARP_5_APPLAUSES: int = const(82)

# A#6 (Helicopter)
# 直升机声
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_SHARP_6_HELICOPTER: int = const(94)

# Standard set sound
# 标准音色
MIDI_PERCUSSION_TIMBRE_5_NOTE_C_7_STANDARD_SET: int = const(96)

# F#7 (Birds)
# 鸟鸣声
MIDI_PERCUSSION_TIMBRE_5_NOTE_F_SHARP_7_BIRDS: int = const(102)

# A#-7 (Seashore)
# 海浪声
MIDI_PERCUSSION_TIMBRE_5_NOTE_A_SHARP_7_SEASHORE: int = const(106)
